DROP TABLE IF EXISTS wcf1_route;
CREATE TABLE wcf1_route (
	routeID INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	route VARCHAR(255) NOT NULL DEFAULT '',
	url VARCHAR(255) NOT NULL DEFAULT '',
	packageID INT(10) NOT NULL DEFAULT 0
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
